name: Rust

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always
  HEAD_REF: ${{ github.head_ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
    - name: Mark whether cache loaded
      run: |
        if [[ -d "target" ]]; then
          echo "cache_loaded=true" >> $GITHUB_ENV
        else
          echo "cache_loaded=false" >> $GITHUB_ENV
        fi
    - name: Git checkout (reattach HEAD to Head Ref)
      run: git checkout "$(echo $HEAD_REF | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref != ''
    - name: Git checkout (reattach HEAD to Ref)
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref == ''
    - name: Install llvm-cov
      run: rustup toolchain install stable --component llvm-tools-preview && cargo install cargo-llvm-cov --force
    - name: Install nextest
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Run tests inc. coverage
      run: cargo llvm-cov nextest --lcov --output-path lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: lcov.info
        verbose: true
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
    - name: Lint check
      run: cargo clippy --all-targets --all-features -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format check
      run: cargo fmt -- --check
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
    - name: Mark whether cache loaded
      run: |
        if [[ -d "target" ]]; then
          echo "cache_loaded=true" >> $GITHUB_ENV
        else
          echo "cache_loaded=false" >> $GITHUB_ENV
        fi
    - name: Setup audit
      run: cargo install cargo-audit
      if: env.cache_loaded == 'false'
    - name: Run audit
      run: cargo audit
